openapi: 3.0.0
info:
  title: Atlas
  description: Esta é uma documentação sobre Atlas API
  version: 1.0.0
paths:
  /users:
    post:
      tags:
        - Users
      summary: Create a user
      description: Create a new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
              example:
                name: User sample name
                email: User sample email
      responses:
        "201":
          description: Created
        "500":
          description: User already exists
    get:
      tags:
        - Users
      summary: List all user
      description: List all users
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    email:
                      type: string
                    admin:
                      type: boolean
        "500":
          description: User already exists
  /{user_id}/admin:
    patch:
      tags:
        - Users
      summary: Make user admin
      description: Make an existent user as admin
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: String ID of the user to make admin
      responses:
        "200":
          description: Success
        "404":
          description: User not found
  /{user_id}:
    get:
      parameters:
        - in: path
          name: user_id
          schema:
            type: string
          required: true
          description: String ID of the user to get
      tags:
        - Users
      summary: List a user
      description: List a specific user
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  email:
                    type: string
                  admin:
                    type: boolean
        "500":
          description: User already exists
